version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@database:1521:ORCLCDB
      - SPRING_DATASOURCE_USERNAME=veterinaria
      - SPRING_DATASOURCE_PASSWORD=veterinaria
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Servicio de base de datos Oracle
  database:
    image: gvenzl/oracle-xe:21-slim-faststart
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin
      - APP_USER=veterinaria
      - APP_USER_PASSWORD=veterinaria
    volumes:
      - oracle-data:/opt/oracle/oradata

# Volumen persistente para datos de Oracle
volumes:
  oracle-data:
    driver: local 